function init(self)
	msg.post(".", "release_input_focus")
	local node_nothing = gui.get_node("nothing_response_parent")
	gui.set_enabled(node_nothing, false)
end


function on_message(self, message_id, message, sender, enter, other_id)
	if message_id == hash("dialogue_choice_nothing") then 
		local node_nothing = gui.get_node("nothing_response_parent")
		gui.set_enabled(node_nothing, true)
	end
end