function init(self)
	msg.post(".", "release_input_focus")
	local node_slimname = gui.get_node("slim_parent")
	gui.set_enabled(node_slimname, false)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("dialogue_response1A_fritz") then 
		local node_slimname = gui.get_node("slim_parent") 
		gui.set_enabled(node_slimname, true)

		msg.post(".", "acquire_input_focus")
		msg.post("/trigger#dialogue_trigger1A_fritz", "disable")
	end
end

