function init(self)
	msg.post("/trigger#dialogue_trigger_nothing", "disable")
	msg.post("/trigger#dialogue_trigger_slim", "disable")
	msg.post("/trigger#dialogue_trigger_perhaps", "disable")
	msg.post("/trigger#dialogue_trigger_stayquiet", "disable")
	msg.post("/trigger#dialogue_trigger_yourname", "disable")
	msg.post("/trigger#dialogue_trigger_youtoo", "disable")


	--WIP test 
	msg.post("/trigger#test_level_loader", "disable")
end
