function init(self)
	local start_pos = vmath.vector3(145, 103, 1)
	go.set_position(start_pos)
end

function on_message(self, message_id, message, sender)
		--Level1A
	if message_id == hash("move_level1A") then 
		local position = vmath.vector3(12851, 886, 1)
		go.set_position(position) 

		--Level1B
	elseif message_id == hash("move_level1B") then 
		local position = vmath.vector3(12851, -902, 1)
		go.set_position(position)
	end
end
