function init(self)
	msg.post(".", "release_input_focus") 
	local node_fritz_parent = gui.get_node("fritz_parent")
	gui.set_enabled(node_fritz_parent, false)
end

function on_message(self, sender, message, message_id)
	if message_id == hash("dialogue_response_fritz") then 
		msg.post(".", "acquire_input_focus") 
		local node_fritz_parent = gui.get_node("fritz_parent")
		gui.set_enabled(node_fritz_parent, true)
		msg.post("/trigger#dialogue_trigger_fritz", "disable")
	end
end
